### ISSUE TITLE
angle constraint can not work

### ISSUE THREAD

**Issue by lelehehele** [solvespace/solvespace#1039]
![image](https://user-images.githubusercontent.com/48273172/118393022-51818580-b66f-11eb-9319-7afa3e996f51.png)
there is a problem, when I change the angle from 20 to 60, or big, it cant not work, but if from 20 to 30, then 30 to 40..... it can work
thanks!
![angle](https://user-images.githubusercontent.com/48273172/118393136-13d12c80-b670-11eb-9dfd-507d65efa008.png)

**Comment by zhulaojianke** [comment]
I cannot reproduce this issue in win7  version e74e2024 :(

**Comment by phkahler** [comment]
@lelehehele  I created a similar diagram and was able to change the angle from 20 to 80 degrees in one step, but not from 10 to 90. I'm not sure what other constraints you've got in there, but this is just the solver having difficulty finding the solution due to the large change and other constraints present. You've already found the solution - make several smaller changes to reach your desired angle. Another option is to drag the sketch close to how you want it prior to adding the constraint.

**Comment by xionghuijiang** [comment]
Actually，there are other constraints
