### ISSUE TITLE
Question about minGW build

### ISSUE THREAD

**Issue by ZehuaZhang** [solvespace/solvespace#1271]
### System information

- **SolveSpace version:** 3.1
- **Operating system:** Windows 10

### Expected behavior

Hit `make` will successfully build solvespace

### Actual behavior

`make` not found

### Additional information

I've followed the [guide](https://code.visualstudio.com/docs/cpp/config-mingw) to install minGW via `MSYS2`, I looked at the minGW install path `bin` folder there's unfortunately no `make.exe`

Another question is that could you tell me why minGW build doesn't have Space Navigator? Is there any way to make it available?

**Comment by ruevs** [comment]
> Another question is that could you tell me why minGW build doesn't have Space Navigator? Is there any way to make it available?

Because of this https://github.com/solvespace/solvespace/blob/master/extlib/si/siapp.lib binary only library, that is in Visual Studio format and so the MinGW linker can not link it.

As for your MSYS2/MinGW installation missing make.exe - it is not in `...\MinGW\bin` it is in `...\msys64\usr\bin` you should have both in your `path`. If you have not rebooted (or logged out and back in) after installing it the path will not be updated. But anyway if you can not figure out your build environment you should ask in a MSYS support forum.
