### ISSUE TITLE
Variagic (multi item) constraints introduced bugs! The equal angle constraint is now impossible to create!

### ISSUE THREAD

**Issue by ruevs** [solvespace/solvespace#1321]
### System information

- **SolveSpace version:** https://github.com/solvespace/solvespace/pull/1314
- **Operating system:** all

### Expected behavior

Be able to create equal angle constraints:

>>> 
                           * four line segments or normals
                                (equal angle between A,B and C,D)
                           * three line segments or normals "
                                (equal angle between A,B and B,C)

https://github.com/solvespace/solvespace/blob/3833dd0246f88e96c5d2a4d83b69b61c760e65ea/src/constraint.cpp#L385
![image](https://user-images.githubusercontent.com/15338069/211102301-282a7174-a026-4d37-b41e-2710ac1c4911.png)

### Actual behavior

This type of constraint is impossible to create after #1314 was merged!

### Additional information

In general #1314 is very suspicious! Already one set of bugs was fixed in https://github.com/solvespace/solvespace/pull/1317 but I suspect there are more.

Further references: https://github.com/solvespace/solvespace/issues/573 https://github.com/solvespace/solvespace/issues/921 https://github.com/solvespace/solvespace/pull/530 https://github.com/solvespace/solvespace/pull/836 https://github.com/solvespace/solvespace/pull/1314

**Comment by phkahler** [comment]
PR #1322 fixes these 2 cases, but the real problem is that pressing "q" with 3 or 4 lines selected already had meaning, and we changed that to make all the line equal length. We don't want to do that. I want to keep the changes, but it looks like a bit more inspection and testing may be needed to make sure there are no other bugs like this.

It may be a good idea to use another key binding "Q" for example for multiple equality constraints, but in most cases that's not really necessary.
