### ISSUE TITLE
Proposal to hide inactive solids

### ISSUE THREAD

**Issue by gabrielmini** [solvespace/solvespace#1328]
Hello everybody!

I'm currently learning about how to use the solvespace. I got a situation that made it difficult to see some sketches in planes using an isometric view. Sometimes, the inactive solid hides the current sketch lines, forcing to draw in a 3d context. To clarify, see the example below:

In this example, we have a 3d view, and a sketch plane in the internal part of this big ring. The main object that I want to extrude, is located inside the red circle:
![image](https://user-images.githubusercontent.com/12013961/211957629-502bcdc3-7498-4968-a1b9-86aa7274b94b.png)

When I align the view to the current workplan, the Inactive solid appears in front of the sketch plane, making (almost) impossible to draw any item Image below:
![image](https://user-images.githubusercontent.com/12013961/211958136-805ed0be-10de-40ea-af69-f52411968a61.png)

The current software version has the option to darken the Inactive solid (Menu-> View-> Darken Inactive Solids), which is good to emphasize the current sketch. However, the situation that I mentioned, doesn't help much. All pictures used here have this option enabled.

My suggestion is to insert a new menu option, or a new icon in Property Browser to completely hide the inactive solid. In this case, will be possible to see the sketch plane without problems.

I don't know if there is someone working on something likely to this, but will be a pleasure to help to develop this enhancement.

Thanks in advance!

### System information
- **SolveSpace version: 3.1~50cbecbe** 
- **Operating system: Ubuntu 22.04.1 LTS**

**Comment by phkahler** [comment]
> I don't know if there is someone working on something likely to this, but will be a pleasure to help to develop this enhancement.

@gabrielmini  If you want to get involved, I see a couple ways this could be improved. For starters, @ruevs shows that the checkbox in the group can be used to "suppress" a groups solid model. What I don't see in the pictures is that once you suppress it, the name of the group on the home screen (text window) is darkened. It has been suggested (there might be an open issue for it?) that there should be a way to toggle group solid model visibility right there on the home screen. We don't want to complicate the UI, and I'm not sure if we have cross-platform support for something like a right-click context menu that could include that toggle.  Darkening the group name was done by someone in order to make it easy to find those groups and turn them back on, but that's only half the challenge. ;-)   Another request has been to make it so mouse over a group name highlights that groups solid model in the sketch, which would make it easier to identify which group to click into and suppress. Another option might be to make the toolbar button (7th one) into a 3-state so it can be used to suppress all solid models rather than just darken them, or add another clickable text link to hide it.

My preference is to add the group solid highlighting on mouse-over in the text window, but I'm not sure how invasive that would be to implement. I suspect it's not too complex if done the "right" way.

**Comment by ruevs** [comment]
Here is the issue requesting to put the check box in the list https://github.com/solvespace/solvespace/issues/1007.

**Comment by gabrielmini** [comment]
> Alternatively the rightmost button in the tool bar of the "Property Browser" window is a three state button that shows hidden lines when it is in this state ![visible](https://raw.githubusercontent.com/solvespace/solvespace/master/res/icons/text-window/occluded-visible.png) or this state ![stippled](https://raw.githubusercontent.com/solvespace/solvespace/master/res/icons/text-window/occluded-stippled.png) :

Cool! Thank you @ruevs for mentioning about this feature, I didn't know that button has three different states. So, in my case, I can see any sketch behind a solid.

**Comment by gabrielmini** [comment]
Hello @phkahler! Thank you for your suggestions! I think all of those features that you mentioned are good options to implement, however, I need to familiarize myself with the code before doing something. In my experience, correcting some bugs is the best way (sometimes hard) to learn fast about some code.

I liked a lot how Solvespace works, and its philosophy. So, will be a pleasure to help and be a small part of it.
