### ISSUE TITLE
Invalid parts linkage in assembly when the folder name has only one char

### ISSUE THREAD

**Issue by RazvanAciu** [solvespace/solvespace#1347]
### System information

- **SolveSpace version:** 3.1~70bde63c
- **Operating system:** Windows 10

### Expected behavior

I have a part file "part.slvs" and an assembly file which refers it in the same folder. If the folder name has more than one char, for example it is named "test", the part file is referred correctly in the assembly file, only with its name "part.slvs".

### Actual behavior

If the folder name is made from only one char, for example "7", after I save the assembly, in the assembly file the part is referred as "7/part.slvs". In this way the part file cannot be found anymore in the assembly, after I restart SolveSpace again and load the assembly.

**Comment by ruevs** [comment]
Note to self:

The bug is around the  `Path Path::RelativeTo` function and more specifically https://github.com/solvespace/solvespace/blob/25b5977962449a734721c667b5347831e8aaa109/src/platform/platform.cpp#L96

This is also related to https://github.com/solvespace/solvespace/pull/1194 - but not the same.

The path handling is rather "baroque" I need to think...
