### ISSUE TITLE
Can't extrude a step-rotated linked sketch

### ISSUE THREAD

**Issue by liuxilu** [solvespace/solvespace#1373]
### System information

- **SolveSpace version:** 3.1~659215d8
- **Operating system:** Win10

### Expected behavior
Sketch is extruded to a solid.
### Actual behavior
Extrude Group error.
### Additional information
[test_AsmExtrude.zip](https://github.com/solvespace/solvespace/files/11612009/test_AsmExtrude.zip)

**Comment by ruevs** [comment]
Disable "g002" in "test_AsmExtrude.slvs". Then the extrude in "test_AsmExtrude.asm.slvs" is OK.

The logic is that all objects that are enabled/visible in a linked file are "present" (imported) in the group in which the file is linked. In your test case this leads to one one of the rectangles being "double" (in g002 and g003). Because of that the extrusion (unsurprisingly) does not work.

![image](https://github.com/solvespace/solvespace/assets/15338069/1e341582-c6f2-4934-86d0-bebe2d5b0443)
