### ISSUE TITLE
unexpected "redundant constraints" for extrusion

### ISSUE THREAD

**Issue by vthriller** [solvespace/solvespace#1391]
### System information

- **SolveSpace version:** 3.1~70bde63c
- **Operating system:** Gentoo Linux

### Actual behavior

![image](https://github.com/solvespace/solvespace/assets/176062/1a06e6d6-d067-4ad9-8975-be32c650ecd1)

### Additional information

No idea how this constraint is "redundant" if, when removed, extrusion depth is no longer fixed.

This is the same model as #1390 with additional "on point" constraint (highlighted on screenshot above) that extends second extrusion to the bottom of the first one.

[wedge-diff-unexpectedly-redundant.slvs.gz](https://github.com/solvespace/solvespace/files/12318105/wedge-diff-unexpectedly-redundant.slvs.gz)

**Comment by phkahler** [comment]
An extrusion has one degree of freedom - how long.  A point on point constraint reduces 3 degrees of freedom - by making the X, Y, and Z value of the point equal. That's why this results in an over constrained sketch.

Try a point-on-plane instead, as that is a 1 DoF constraint.

**Comment by ruevs** [comment]
The points coincident constraint is indeed redundant, since (in 3d) it removes three degrees of freedom and the extrusion `g005-extrude` only has one.

![image](https://github.com/solvespace/solvespace/assets/15338069/2f2d0d0a-eac3-473d-8d6f-c062e01cf941)

To achieve what you want set the point to be on the "bottom" face:

![image](https://github.com/solvespace/solvespace/assets/15338069/07a18ece-2eea-4343-b4ef-d207ffcb0108)

Then you will have 0 DOF and no redundant constraints:

![image](https://github.com/solvespace/solvespace/assets/15338069/9215b7ea-6ff8-46bb-a498-372592a36476)
