### ISSUE TITLE
what is the meaning of drag conception in the code？

### ISSUE THREAD

**Issue by ziyuanbaby** [solvespace/solvespace#1473]

**Comment by ruevs** [comment]
What is a "drag conception"?

**Comment by ruevs** [comment]
See here:
https://github.com/solvespace/solvespace/issues/1471#issuecomment-2222888883
the size is 4 because...  @jwesthues [decided like this 15 years ago](https://github.com/solvespace/solvespace/blame/2afabadfa5e21ad37dfcac24cf8244e2ffcdbd78/include/slvs.h#L165)?

In SolveSpace itself it is a list - as big as needed.
