### ISSUE TITLE
Show units of dimensions in more precise way

### ISSUE THREAD

**Issue by Evil-Spirit** [solvespace/solvespace#227]
This commit introduces units in meters https://github.com/Evil-Spirit/solvespace-master/commit/bc3e7a2e11d5e363d24d224b31df00013a996dfe
This https://github.com/Evil-Spirit/solvespace-master/commit/202c6fbb94297b0e632076dd22a5eeed47b6fba1 is experiments with si prefixes and formatting

![2017-04-06 20 08 41](https://cloud.githubusercontent.com/assets/1980537/24755691/61d5b046-1b05-11e7-9679-97445572a5ff.png)
![2017-04-06 20 10 42](https://cloud.githubusercontent.com/assets/1980537/24755695/63eb2244-1b05-11e7-908d-7bbfe556f4d4.png)
![2017-04-06 20 12 03](https://cloud.githubusercontent.com/assets/1980537/24755696/655e86b6-1b05-11e7-95dd-9c9da49248ab.png)

**Comment by whitequark** [comment]
Thank you for this excellent feature! I've merged the "dimensions in meters" patch in master. Do you think you could add "Dimensions with _S_I prefixes" as another menu option? This seems to be more in line with the rest of the options.

**Comment by Evil-Spirit** [comment]
You mean to make this feature as option to have ability to switch it off?

**Comment by whitequark** [comment]
I mean it makes sense to have separate options for "dimensions in mm" (for ISO technical drawings), "dimensions in m" (for architectural drawings) and "dimensions in metric with SI prefixes" (for unusual drawings where very large, very small or very different units are present). This is because most technical drawings have all length dimensions with the same units to make it less likely that e.g. someone misreads "mm" as "m" or maybe "cm".

**Comment by Symbian9** [comment]
@whitequark, would you also merge "don't show zeroes" option?

**Comment by whitequark** [comment]
@Evil-Spirit Thank you, merged in bc0e9c5, with many changes:
  * Added cm;
  * Added imperial units (mil, µin);
  * Changed formatting to use round-to-even, to match labels displayed with SI units off;
  * Adjusted measurement tools to always use SI prefixes, because 400000000 mm³ is not a useful value;
  * Overall simplification.
