### ISSUE TITLE
Enhancement : Allow change of default of not allowing redundant constraints. 

### ISSUE THREAD

**Issue by mmiscool** [solvespace/solvespace#27]
I would like to be able to change a setting that makes it so that the check box for allowing redundant constraints can be turned on by default and turned off at user discretion.

**Comment by whitequark** [comment]
Sorry, no, this is a bad idea. The solver does not handle redundant constraints well, and it is unlikely that you will be able to do anything complicated with the redundant constraints allowed. The mode exists solely in order to constrain assemblies, where positioning them in 3d without overconstaining is very awkward.

**Comment by whitequark** [comment]
(On top of that you will find that reducing the amount of constraints to the bare minimum lets you produce sketches that are much easier to modify.)
