### ISSUE TITLE
Image transparency/opacity

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#343]
### System information

SolveSpace version: 3.0~8426992f

Operating system: Debian 9 "Stretch"

### Expected behavior

After "Sketch Image" there should be a way how set image transparency/opacity.

Alternatively add support for PNG with ARGB colors (with transparency), so user can prepare image with transparency before import it to SolveSpace.

### Actual behavior

Currently there no way how to set transparency/opacity for imported *Image*.

Also, actually SolveSpace not support PNG with ARGB colors (SolveSpace import it as PNG with RGB colors, without transparency).

### Additional information

![pic1](http://pasteall.org/pic/show.php?id=155614259b1604deaadb0c757a2824b0)

**Comment by whitequark** [comment]
The PNG format, of course, supports transparency, here is a PNG with a transparent cutout:
![test](https://user-images.githubusercontent.com/54771/43356382-73d911f2-925f-11e8-85d0-d2b351a4309f.png)

There is no need for support of APNG, because the only thing APNG adds is support for animation.

**Comment by Symbian9** [comment]
> There is no need for support of APNG

Oh, sorry. Yes, I mean PNG with ARGB colors.

Currently SolveSpace suport only PNG with RGB colors.

**Comment by whitequark** [comment]
That's not true. SolveSpace supports ARGB PNGs just fine. The problem is that rendering transparent geometry is hard because it is order dependent, and proper support for transparent geometry is a very significant task that is outside of scope of what SolveSpace tries to achieve.

However, that doesn't mean that we can't support PNGs with holes in them, i.e. with pixels that have alpha set to zero exactly. This is now supported in 2b4c484:
![screenshot_20180728_123138](https://user-images.githubusercontent.com/54771/43356580-b415f87c-9262-11e8-8351-86cd3deab733.png)

To reiterate, *blending* PNGs with pixels that have alpha between 0.0 and 1.0 is not supported (and probably will not be supported), and any pixels with non-zero alpha will appear opaque.

**Comment by Symbian9** [comment]
> However, that doesn't mean that we can't support PNGs with holes in them, i.e. with pixels that have alpha set to zero exactly. This is now supported
Thanks, this would be very useful! ;-)

But, is there a way to apply opacity to "extrude" group with *Image*? Or its fully impossible too?

![pic1](http://pasteall.org/pic/show.php?id=24404962211d7d8959f1156e221fe205)

**Comment by whitequark** [comment]
You can't extrude images directly. Trace the image using SolveSpace entities and extrude that instead.

**Comment by Symbian9** [comment]
> You can't extrude images directly. Trace the image using SolveSpace entities and extrude that instead.

No, I not try extrude image to 3D model (I now that it's impossible)

I mean that opacity option now shown only in "extrude"/"lathe"/"assemble" groups.

As "sketch-in-plane" has no opacity option, I just make "extrude" group from "sketch-in-plane" with *Image* (you can see it on screenshot).

**Comment by whitequark** [comment]
The opacity option only affects geometry. It won't work on image requests.

**Comment by Symbian9** [comment]
> It won't work on image requests.

Okay...
