### ISSUE TITLE
Extrude quietly fails to produce a solid on self-intersecting sketches

### ISSUE THREAD

**Issue by vcaputo** [solvespace/solvespace#352]
### System information
x86_64

SolveSpace version: 2.3

Operating system: (e.g. Debian testing)
debian 9.5

### Expected behavior

What should have happened?

Produce a solid.

### Actual behavior

What actually happened?

Not a solid.

### Additional information

See the attached slvs file, there's no feedback stating the step-rotate-repeated sketch which was extruded has a self-intersecting center line preventing the extrude from succeeding.

Removing the center line or "toggle construction" on that line in the sketch makes things work.

[notsolid.slvs.zip](https://github.com/solvespace/solvespace/files/2377683/notsolid.slvs.zip)

Furthermore, if the order is simply switched to sketch->extrude->step-rotate-repeated, the centerline doesn't matter and a solid is produced.  It's rather confusing.

**Comment by phkahler** [comment]
There is an indication that the rotate group can not be extruded. The area of the shape is filled in with a light gray when it is a complete, non-intersecting shape. Your background is solid black. Since this seems to be detected, it may be possible to issue a message about it when you try to extrude. Would that be enough?.

Sometimes you can manipulate the underlying sketch after doing an extrusion and that can change it to/from self intersecting. Try extruding a pentagon and then take one vertex and drag it across the opposite side - the solid will disappear and reappear as you make the shape intersect or not.

**Comment by whitequark** [comment]
Fixed in df6777a.
