### ISSUE TITLE
Feature - New Group: Spiral (flat spiral)

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#426]
### Expected behavior

Add "Spiral" tool for creating flat spirals:

- spiral of Cornu;
- hairspring (balance spring);
- etc.

It could be realized in two ways:

1. as "Sketch" tool: 1) draw spiral in plane; 2) then extrude it (cons - spirals profile always would rectangular)
2. as "New Group" tool: 1) draw profile; 2) create/rotate spiral.

Second variant is preferred.

Or as option such as "Helix" for "Lathe" tool: https://github.com/solvespace/solvespace/issues/389

### Additional information

![pic.1](https://upload.wikimedia.org/wikipedia/commons/2/22/Balance_spring_types.png)

**Comment by whitequark** [comment]
I don't think SolveSpace should gain a generic planar spiral generator. Make a spiral elsewhere and export a DXF, then extrude; that would be far more efficient.

**Comment by Evil-Spirit** [comment]
NoteCAD have "function" entity to create such curves like this
catenary a
![D0oJn5OXcAAA8tr](https://user-images.githubusercontent.com/1980537/59345624-b07b4900-8d3a-11e9-90ec-6ab21dc030c4.jpg)
rch
cornu spiral based on fresnel integrals
![D0oFS2RXcAA4HNl](https://user-images.githubusercontent.com/1980537/59345647-c4bf4600-8d3a-11e9-8821-e48fb6c3241b.png)

**Comment by Symbian9** [comment]
> NoteCAD have "function"

Would be happy to see this in SolveSpace too.

**Comment by Evil-Spirit** [comment]
> Would be happy to see this in SolveSpace too.

SolveSpace's solver has born to has freature like this.

**Comment by Symbian9** [comment]
> SolveSpace's solver has born to has feature like this.

But would be it possible draw Euler spirals and extrude along Euler spiral in SolveSpace? (spiros, clothoids, or Cornu spirals)

**Comment by Evil-Spirit** [comment]
I don't know. If anyone will implement it. NURBS approximation of such functions can be rather complicated task. NURBS actually not an advantage for SolveSpace at the moment. Too many people want to help but can't because of buggy (from one side) and too complicated (from the other side) of NURBS backend. I think SolveSpace can't beat commercial software, so not necessary to try do that. Instead, SolveSpace can utilize some proven OpenSource geometric libraries like CGAL which provide slow but really robust booleans based on Nef Polyhedra algorithms. So, for realtime geometric computations, SolveSpace can use fast BSP and for export - slow but good quality CGAL. If this step will be performed, any of  geometric functions like extrusion along path will be much simplier in implementation and probability of happening of such implemetation will increase.

**Comment by Evil-Spirit** [comment]
For the record. I have implemented helical revolve for NoteCAD in 2 evernings. That's because I have no any NURBS.

**Comment by whitequark** [comment]
@Evil-Spirit If there is no NURBS, there is no STEP export that machine shops can take. That would make SolveSpace mostly useless for me. Maybe I could still use it for 3D printing (not that I do a lot of it), but I will need another CAD for any serious machining work, so why bother maintaining it?

**Comment by Evil-Spirit** [comment]
@whitequark I understand.

**Comment by stefano2734** [comment]
See Levien PHD for better bezier curves also
Inkscape spiro curves are from Levien.

https://levien.com/spiro/
https://levien.com/phd/thesis.pdf

**Comment by ruevs** [comment]
> See Levien PHD for better bezier curves also Inkscape spiro curves are from Levien. https://levien.com/spiro/ https://levien.com/phd/thesis.pdf see page 152 in pdf (135 in text) for optimized bezier curves.

This would be relevant is one day we decide to implement spirals or curves based on "any fuction". My detailed response is here https://github.com/solvespace/solvespace/issues/1447#issuecomment-1934077135
