### ISSUE TITLE
Helix tool almost always results in invalid mesh

### ISSUE THREAD

**Issue by andres-erbsen** [solvespace/solvespace#550]
### System information

dcc80de on Arch Linux

### Expected behavior

A manifold mesh representing the helical extrusion, for example

![c](https://user-images.githubusercontent.com/918403/74096987-4d61d200-4ad4-11ea-9d40-6f1e745e67ae.png)

### Actual behavior

If I increase the angle just a bit I get a self-intersecting mesh:

![d](https://user-images.githubusercontent.com/918403/74097001-944fc780-4ad4-11ea-9ca5-4739a5b0e2ca.png)

and increasing the angle just slightly more gives naked edges instead:

![b](https://user-images.githubusercontent.com/918403/74096990-5ce11b00-4ad4-11ea-809f-cbd822363ab7.png)

### Additional information

Note that the issues are present even with "force NURBS surfaces to triangle mesh".

This example (unit square at unit distance from axis): [helix.zip](https://github.com/solvespace/solvespace/files/4176517/helix.zip)
Non-trivial example (8x rotated 2 beziers approximating involute that is almost a triangle): [gear90.zip](https://github.com/solvespace/solvespace/files/4176518/gear90.zip)
This also occurs when applying helix to a circle.

#472 seems relevant.

**Comment by phkahler** [comment]
The problems with helix.zip seem to be solved by #473 which is very helpful for extrusions with a lot of twist. No naked edges.

Basic rendering with gear.zip is also better with those changes. There are fewer errors when using Analyze -> show naked edges but there are still a lot of them with that model. I'm not sure what causes them in that case - lowering the chord tolerance causes more of them.

**Comment by mkyral** [comment]
Hi,
I've played with Helix (really useful tool) in and I've generated this problematic shape: [rounded_edges_issue.zip](https://github.com/solvespace/solvespace/files/4664827/rounded_edges_issue.zip)

![obrazek](https://user-images.githubusercontent.com/155542/82607196-b0293600-9bb8-11ea-8d4f-e171cf2d2aa8.png)
![obrazek](https://user-images.githubusercontent.com/155542/82607447-1910ae00-9bb9-11ea-92e4-2130868bd8ac.png)
![obrazek](https://user-images.githubusercontent.com/155542/82607737-a48a3f00-9bb9-11ea-9893-42e569bdac3d.png)

**Comment by phkahler** [comment]
@mkyral  You can fix the naked edges problem (sort of, I hate the need to do this) by clicking on g005-helix in the text window. Then check the box for "force NURBS surfaces to triangle mesh. SolveSpace has some NURBS issues, but NURBS are preferable to meshes so long as those issues don't show up. I tried a reconstructing the curve sketch differently but ran into the same issue.

A suggestion about the design. If you're not going to slide the opening to the side, use a reVolve instead of a Helix. It doesn't solve the issue here, but SolveSpace then recognizes the flat surfaces on the sides as flat (you can select them and constrain things to them). Also go to home->configuration->chord tolerance and lower that value to 0.1 it will look a little better on-screen (lowering that too much will degrade performance).

**Comment by mkyral** [comment]
Hi,
Thanks for your suggestions. ReVolve works better in this case.

**Comment by phkahler** [comment]
While experimenting with variations on grid triangulation I noticed that changes to the interior grid can affect the number of naked edges on that gear90 model. This has me thinking it's an issue with ear triangulation on a helix, since the grid has no effect on outer edges.

Speculations: maybe a problem with very narrow triangles, or near nonlinear segments.

**Comment by phkahler** [comment]
@andres-erbsen The rest of this is fixed in PR#643 The gear90 model will have no naked edges if chord tolerance is set to either 0.5 or 0.2.  They do reappear when its set to 0.1 though so it's not the ultimate fix, just a good improvement.

I am curious why you made the gear teeth with that type of curve. Would an arc be OK? How about one cubic bezier for each side of the tooth? Those would create more uniform curve segments which may help. I'm not a gear expert so I don't know what's more accurate.

**Comment by andres-erbsen** [comment]
Thanks!

I'm no expert either; I think I was following [this tutorial](https://www.youtube.com/watch?v=i6tDWJsNsok) for the bezier approximation of the common [involute gear](https://en.wikipedia.org/wiki/Involute_gear) profile. I tried the same with a single cubic bezier just now and I was able to get it within fabrication tolerance of what I want in this example. The linked construction is neat, though, because it doesn't require eyeballing the locations of the control points (but doing this construction with just two control points gives a straight line).
