### ISSUE TITLE
Add "Comment" on right click menu if nothing selected

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#58]
Currently if nothing selected right click menu (contextual menu) is empty.

Propose add "Comment" operation in this menu if nothing (instrument or element) selected.

**Comment by whitequark** [comment]
Actually, there's "Select all", which makes sense because all selection operations are accessible via the context menu.

But I don't see why comments should be privileged over any other sketch tool. Like with #33, you probably want https://github.com/whitequark/solvespace/issues/117 if you would like to place a large number of comments (points, constraints, etc).
