### ISSUE TITLE
Redundant constraints are treated as errors

### ISSUE THREAD

**Issue by dims12** [solvespace/solvespace#671]
### System information

SolveSpace version: 2.3~7c1ca460

Operating system: Windows 10 Pro

### Expected behavior

Redundant (not contradicting, but telling the same) constraints should be ok.

### Actual behavior

In case of redundant constraints, the program says "solve failed", which is wrong.

### Additional information

Redundant triangle attached

[redundant.zip](https://github.com/solvespace/solvespace/files/5042782/redundant.zip)

**Comment by whitequark** [comment]
In group options you can tick the "allow redundant constraints" checkbox to suppress the error. However, SolveSpace's constraint solver does not handle many kinds of redundant constraints very well, which is why this is an error by default. Because it may significantly impair convergence, I recommend avoiding this option other than for assemblies.

**Comment by phkahler** [comment]
@dims12 You can also select one of the angle constraints and convert it to a reference dimension "REF" on the toolbar. Then it will show the angle but not add the redundant constrain. Version 3 will do this automatically when the 3rd constraint is added.
