### ISSUE TITLE
Represent angle as 0°-360°

### ISSUE THREAD

**Issue by Symbian9** [solvespace/solvespace#82]
Represent angle as 360° for full revolution/circle.
0° must be deferent from 360°, because 0° - define start of revolution/circle, 360° - finished revolution/closed circle.

**Comment by jwesthues** [comment]
[0,360) maybe someday, [0,360] no. Think, for example, of what that would mean to the present arc representation.

I'd suggest that you more closely study the mathematical structure of our current solver, and the manner in which entities and constraints are represented. This will help you to suggest enhancements that are practical in that context.

**Comment by Symbian9** [comment]
No, I mean, that for rotate element we need "Rotate" constraint.
There no need tell "Rotated to 2000°", instead "Rotate to 5.2 revolution".

Angle must be [0, 360] !

**Comment by jwesthues** [comment]
Are you referring to step rotating groups? The total angle there can meaningfully equal or exceed a full revolution, since the angles between individual copies are less than that. That works in the obvious way already.

What are you actually trying to do? If you give an example of the problem that you're trying to solve, then perhaps we'll understand better.

**Comment by Symbian9** [comment]
@jwesthues, I mean that rotating and angle must be two different constraints https://github.com/solvespace/solvespace/issues/83

P.S.: "New group step and repeat rotating" is from other story there.
